### ISSUE TITLE
backend.py Not working

### ISSUE THREAD

**Issue by gamingsugo** [kevinjycui/DesmosBezierRenderer#12]
Backend.py is giving me the following error

` Processing 1 frames... Please wait for processing to finish before running on frontend

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "backend.py", line 87, in get_expressions
    for expr in get_latex(FRAME_DIR + '/frame%d.%s' % (frame+1, FILE_EXT)):
  File "backend.py", line 62, in get_latex
    path = get_trace(get_contours(filename))
  File "backend.py", line 36, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "backend.py", line 107, in <module>
    frame_latex = pool.map(get_expressions, frame_latex)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor' `

Did I do something wrong?

**Comment by rvjanapin** [comment]
did you follow this
![image](https://user-images.githubusercontent.com/80207044/118246454-8d341800-b4d4-11eb-9e21-52b02f7e5768.png)
i got the same error until i fixed the filenames hope this helps

**Comment by gamingsugo** [comment]
I double checked and the file names should be correct. But it still errors for me.
![image](https://user-images.githubusercontent.com/35443465/118268459-67ceec00-b48b-11eb-8af7-21b927dd40cb.png)

![image](https://user-images.githubusercontent.com/35443465/118268555-8339f700-b48b-11eb-9823-fddfd8808193.png)

**Comment by gamingsugo** [comment]
I printed out some of the variables from the script to see if it could help someone solve my issue. It might have to do that I dragged the image into the frames directory, is it supposed to be done like that?
![image](https://user-images.githubusercontent.com/35443465/118314204-cc0ca280-b4c1-11eb-984a-cd600b513b80.png)

**Comment by gamingsugo** [comment]
Ok I found my own solution. I tried using plt to read the image and it gave a better error message where python didn't have enough permission to access the image so I just used this which fixed it for me. '

chmod 755 image_name.png
