### ISSUE TITLE
NameError: name 'frame' is not defined

### ISSUE THREAD

**Issue by NotSoNooby** [kevinjycui/DesmosBezierRenderer#18]
Traceback (most recent call last):
  File "/Users/userdir/DesmosBezierRenderer/backend.py", line 108, in <module>
    frame_latex = pool.map(get_expressions, frame_latex)
  File "/Users/userdir/bin/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/userdir/bin/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
NameError: name 'frame' is not defined

**Comment by NotSoNooby** [comment]
fixed.

**Comment by AaaaronH** [comment]
Ummm. How did you fix it?

**Comment by NotSoNooby** [comment]
it was brew's fault so i just ran it on an Ubuntu VM.

**Comment by ngzhaoming** [comment]
I managed to solve this issue by shifting the lines 190 - 193 to line 36 - 39 instead, make sure that ```frame_latex =  range(len(os.listdir(FRAME_DIR)))``` originally in line 193 comes after the line ```FRAME_DIR = 'frames' # The folder where the frames are stored relative to this file``` in line 26.

I managed to run this on macOS

**Comment by kevinjycui** [comment]
> I managed to solve this issue by shifting the lines 190 - 193 to line 36 - 39 instead, make sure that `frame_latex = range(len(os.listdir(FRAME_DIR)))` originally in line 193 comes after the line `FRAME_DIR = 'frames' # The folder where the frames are stored relative to this file` in line 26.
> 
> I managed to run this on macOS

Incorporated this change in the program. My guess for why these issues are happening is that just different machines are taking different amounts of time to complete the multiprocessing jobs and sometimes the order gets mixed up?

**Comment by ngzhaoming** [comment]
> > I managed to solve this issue by shifting the lines 190 - 193 to line 36 - 39 instead, make sure that `frame_latex = range(len(os.listdir(FRAME_DIR)))` originally in line 193 comes after the line `FRAME_DIR = 'frames' # The folder where the frames are stored relative to this file` in line 26.
> > I managed to run this on macOS
> 
> Incorporated this change in the program. My guess for why these issues are happening is that just different machines are taking different amounts of time to complete the multiprocessing jobs and sometimes the order gets mixed up?

Hmmm, I'm not too sure myself, but yeah I guess it has to do with the multiprocessing jobs not being executed in order. Nonetheless, great project btw!
