### ISSUE TITLE
Potential fix for ugly doublelines

### ISSUE THREAD

**Issue by junqiwu02** [kevinjycui/DesmosBezierRenderer#2]
Have you considered using a centerline tracing library to vectorize the OpenCV contour bitmaps? Centerline would create a single line in the center of each stroke instead of the ugly doublelines that you are getting with Potrace.

Really liked your youtube video btw!

**Comment by kevinjycui** [comment]
Does centerline tracing return Bezier curves? The OpenCV contours are already vectorised by default, but since they yield straight lines, they are converted to bitmaps. The reason why potrace is used is so that the lines can be represented as curves and thus use less expressions.

**Comment by junqiwu02** [comment]
You may be right, I wasn't able to find any Python libraries with a quick Google search that explicitly return Bezier curves.
I was thinking of [Autotrace](https://github.com/autotrace/autotrace) which does centerline tracing with Bezier curves, but that's a standalone program.

Although if the main goal is to reduce the curve count, running cv2.findContours() with cv2.CHAIN_APPROX_SIMPLE instead of cv2.CHAIN_APPROX_NONE may net you a low enough number of lines to be directly rendered by Desmos.

**Comment by kevinjycui** [comment]
`cv2.CHAIN_APPROX_SIMPLE` will lower the resolution, and it still does not resolve the issue (only reducing the number of contours in a straight line, doesn't deal with lines in a curve). Autotrace is just another bitmap to vector graphics converter, with the same functionality as Potrace. From what I can tell, running Autotrace on the contour image should be identical to running Potrace on the contour image. Closing this issue for now.
