### ISSUE TITLE
Feature To Add - Export to Desmos Website

### ISSUE THREAD

**Issue by BarelyOutOfTuesday** [kevinjycui/DesmosBezierRenderer#20]
Hi guys, Great project! One feature I would suggest is to add the option to export the official Desmos website - so one can save a frame as a file - and then share it with people????
Regards,

**Comment by Green-Thanos** [comment]
You could probably make your own system for saving desmos files, but I dont think theres anything native that desmos has

**Comment by Zyrusse** [comment]
> Hi guys, Great project! One feature I would suggest is to add the option to export the official Desmos website - so one can save a frame as a file - and then share it with people???? Regards,

https://github.com/kevinjycui/DesmosBezierRenderer/issues/33
Does my post answer your suggestion?

**Comment by timmy76767** [comment]
for command python3 backend.py -h
Traceback (most recent call last):
  File "backend.py", line 2, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

What does this error mean and how do I fix it?

**Comment by Maxxxutko** [comment]
> for command python3 backend.py -h Traceback (most recent call last): File "backend.py", line 2, in from flask import Flask ModuleNotFoundError: No module named 'flask'
> 
> What does this error mean and how do I fix it?

Hi there! You need go and install Flask module, use this command: pip install flask
