### ISSUE TITLE
Blank Desmos Page

### ISSUE THREAD

**Issue by Green-Thanos** [kevinjycui/DesmosBezierRenderer#21]
After getting rid of all errors, when I set f=1 on the page, the grid lines remove, but the page is blank. Im using the sample image provided in the github folder.
The screenshot after is also blank. 
What could be the issue?

**Comment by imon00** [comment]
Hi, I am very excited about this project. I have tried in Ubantu and Linux mint, ( on virtual box) , overcoming all errors, all I get a blank page of Desmos with grid  on both Ubantu and Linux Mint. Not only that I have had two equations and when I put f=1 and press the play button, after some time the grid vanishes and a download box arrives which contains a picture like Figure 2. I have used both the example picture and my own picture, but at both time the results are same. 
![Github](https://user-images.githubusercontent.com/67217470/121115019-600a2980-c836-11eb-926e-7624415fdeff.png)
![Git 2](https://user-images.githubusercontent.com/67217470/121115045-6e584580-c836-11eb-96ae-4070b191fab8.png)

**Comment by Green-Thanos** [comment]
These sre the same results im getting. Notice that in the python file, in the get_contours function, all the code after frame.get_lock() never runs. This is also where the height and width are defined. I think this is the reason for a height and width of 0 being sent to the page and therefore being blank. I hope either I or someone else can fix this!

**Comment by imon00** [comment]
I hope that @kevinjycui will fix that or give us a solution.

**Comment by kevinjycui** [comment]
@Green-Thanos @imon00 If a download prompt appears it means that the image is rendering successfully. I notice in your screenshot that the Desmos graph is only showing a 10x10 area above the x and y axis. Note that the rendering is 1:1 to the dimensions of the image, and so if the image is 480x480p for example, the image will render on x ∈ (0, 480) and y ∈ (0, 480). Try zooming out to the correct dimensions before setting `f=1`. If you don't want to remove gridlines upon rendering, you can set `SHOW_GRID=True` in `backend.py`.

**Comment by Green-Thanos** [comment]
smh im so dumb

One last question, is there a way to stop it instead of reloading and resetting the page, and is there a way to show the equations? Like the uncommenting with json.dumps('cache.json'

**Comment by imon00** [comment]
Now I get it. Thanks man. Eagerly waiting for more exiting projects, 😀😀
@kevinjycui

**Comment by kevinjycui** [comment]
Glad I could help!
