### ISSUE TITLE
Fail to draw graph

### ISSUE THREAD

**Issue by Klefo0** [kevinjycui/DesmosBezierRenderer#24]
So I have setup a virtual machine, install all requirements in right version, then I have two png file, each file is a graph. I'm using it to find if it have any function suit with those graph, but when app gave me two image, nothing in it except white.

**Comment by TrunkMonkee** [comment]
I'm having the exact same problem. I think it's something with either the generation of the Latex formulas, or the transfer of the formulas to desmos. Let me know If you find anything.

**Comment by TrunkMonkey5850** [comment]
Mine is currently working. Try making the ```frame1.png``` image the ```sample.png``` image from the github folder.

**Comment by Klefo0** [comment]
Someone on Junferno's Discord server said the renderer cannot solve and give the mimick of the graph
