### ISSUE TITLE
Desmos unloads the rendered image

### ISSUE THREAD

**Issue by Nekoma-Ayaya** [kevinjycui/DesmosBezierRenderer#30]
Hi! I have been trying to run the program via WSL for sometime now, but i can't figure out why desmos keeps removing the image. After starting backend.py, I boot up the index.html, and put f=1 in the equation, to which Desmos responds with l="some value" and starts the render. But, after a couple of seconds, the l value returns to 0, and the whole desmos graph is back to empty (I have read in a issue post that a download prompt appears, but nothing of that sort happens for me). I can guarantee the image starts rendering, but disappears suddenly.

Is there something I am doing wrong? Any help would be much appreciated.

**Comment by kevinjycui** [comment]
This is the intended behaviour of the program. You can enable the download prompt by running it as
```sh
python3 backend.py -d
```
Otherwise, if you want the last frame to stay as it is, the only way to remove this behaviour without modifying the code yourself is to revert the program to the commit before it was implemented using
```sh
git checkout 47b10ea98b04b98ce46e54a46adde27bcb52e53e
```
Note that this may cause the rendering to be significantly slower, though it would be identical to the program used in the video demo.

**Comment by Nekoma-Ayaya** [comment]
Thank you. I have reverted to the old commit, but now Desmos shows no equations or graphs. Nothing at all. No f="sth" or anything. Again, any help will be appreciated :)

**Comment by kevinjycui** [comment]
@Nekoma-Ayaya In the old version, note that the process to run the script is different. Once you've loaded your HTML file, open the developer console (Ctrl+Shift+I and then select the "Console" tab on chromium) and run `init()`. This is detailed in the [README of the old version](https://github.com/kevinjycui/DesmosBezierRenderer/blob/47b10ea98b04b98ce46e54a46adde27bcb52e53e/README.md)

**Comment by Nekoma-Ayaya** [comment]
Thanks a lot! It's working perfectly. A bit slow, but since I want images, it's okay. 

Thanks again!

**Comment by kevinjycui** [comment]
This has now been fixed for the current main branch!
