### ISSUE TITLE
how do I see the equations it's using?

### ISSUE THREAD

**Issue by Zyrusse** [kevinjycui/DesmosBezierRenderer#32]
![image](https://user-images.githubusercontent.com/36795942/138551236-83f0d783-6af7-4332-921b-f44d57780511.png)

**Comment by kevinjycui** [comment]
I'm not too certain why the equations are no longer shown, but it could be a byproduct of the optimisations. If efficiency is not too big of an issue with your rendering, you can always revert the code to before the optimisations with `git checkout 47b10ea98b04b98ce46e54a46adde27bcb52e53e` and try running it like that (note that this *will* cause your rendering to be slower).

**Comment by kevinjycui** [comment]
Also note that if you revert it, you have to run it by running `init()` in your browser's console instead (which you can find using Ctrl+Shift+I on chromium)

**Comment by kevinjycui** [comment]
This has now been fixed for the current main branch!
