### ISSUE TITLE
Copying all equations (this is for rendering 1 image)

### ISSUE THREAD

**Issue by Zyrusse** [kevinjycui/DesmosBezierRenderer#33]
Is this possible?

**Comment by kevinjycui** [comment]
There's no built-in way to copy them to the clipboard. I made a mistake in my previous answer. Try opening `localhost:5000/?frame=0` instead.

**Comment by Zyrusse** [comment]
> There's no built-in way to copy them to the clipboard. I made a mistake in my previous answer. Try opening `localhost:5000/?frame=0` instead.

Sorry for the late reply. Thanks, that worked. I believe this answers the other issue (exporting a frame to the actual website)
![image](https://user-images.githubusercontent.com/36795942/140600279-5d5156dd-8327-4381-a679-c3c85d49ac6c.png)

**Comment by kevinjycui** [comment]
Great!

**Comment by Cyber-Phantom** [comment]
> > There's no built-in way to copy them to the clipboard. I made a mistake in my previous answer. Try opening `localhost:5000/?frame=0` instead.
> 
> Sorry for the late reply. Thanks, that worked. I believe this answers the other issue (exporting a frame to the actual website) ![image](https://user-images.githubusercontent.com/36795942/140600279-5d5156dd-8327-4381-a679-c3c85d49ac6c.png)

May i know how you imported the raw data into desmos afterwards

**Comment by jan-ale** [comment]
Most likely copied and pasted it

**Comment by FlapJakx** [comment]
> > There's no built-in way to copy them to the clipboard. I made a mistake in my previous answer. Try opening `localhost:5000/?frame=0` instead.
> 
> Sorry for the late reply. Thanks, that worked. I believe this answers the other issue (exporting a frame to the actual website) ![image](https://user-images.githubusercontent.com/36795942/140600279-5d5156dd-8327-4381-a679-c3c85d49ac6c.png)

Sorry, how have you managed to transfer the raw data into desmos?
