### ISSUE TITLE
running html file gives Error code: RESULT_CODE_KILLED_BAD_MESSAGE on windows

### ISSUE THREAD

**Issue by No-Time-To-Explain** [kevinjycui/DesmosBezierRenderer#34]
After following the guide provided, I tried running the index.html file to render an image, yet every time I do so, it kills the page and gives me Error code: RESULT_CODE_KILLED_BAD_MESSAGE.
The only thing I have done differently is update numpy so that I could avoid an error with potrace, and it seems to have worked fine with it updated, yet it could possibly be the issue. Is there any other issue I could be running into that could cause the error?

**Comment by Klebster755** [comment]
Same thing here, any luck with the solution?
