### ISSUE TITLE
Difficulty adding images to 'frames' directory

### ISSUE THREAD

**Issue by BigSweaterMan** [kevinjycui/DesmosBezierRenderer#43]
I am a complete beginner, so please forgive the stupidity.
I'm working on a windows system. WSL is downloaded, but I can't figure out how to put files from a windows directory (a folder on my desktop) to a directory that I can call with this code.
README says to create a directory:
`mkdir frames
...`
but not how to add files to it.
Again any help is much appreciated.

**Comment by kevinjycui** [comment]
Try running this command to open the file explorer from WSL:
`explorer.exe .`

**Comment by BigSweaterMan** [comment]
Thank you!
