### ISSUE TITLE
Error running backend.py

### ISSUE THREAD

**Issue by UntitledShovel** [kevinjycui/DesmosBezierRenderer#44]
`Traceback (most recent call last):`
`  File "backend.py", line 8, in <module>`
`    import potrace`
`  File "/home/sargo/.local/lib/python3.8/site-packages/potrace/__init__.py", line 1, in <module>`
`    from potrace._potrace import *  # NOQA`
`  File "potrace/_potrace.pyx", line 1, in init potrace._potrace`
`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Comment by gooday2die** [comment]
I also had the same issue with potrace. 
According to [Here](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp), it seems like numpy's version might have something with the issue.

In my case, `pip install --upgrade numpy` fixed the problem.
