### ISSUE TITLE
error at frontend

### ISSUE THREAD

**Issue by qalassa** [kevinjycui/DesmosBezierRenderer#47]
The entire process worked properly, but when loading index.html there are no results, I got an idea to do inspect and see console, and that was showing this error:

index.html:29          GET http://127.0.0.1:5000/init net::ERR_SOCKET_NOT_CONNECTED
(anonymous) @ index.html:29

any help?

**Comment by kevinjycui** [comment]
Did you put `f=1` into the first formula in the formula window?

**Comment by qalassa** [comment]
Yes, I put it but with no results,  hopefully you help me.
