### ISSUE TITLE
after completing backend.py code Im getting a win error 3

### ISSUE THREAD

**Issue by sambuddha05** [kevinjycui/DesmosBezierRenderer#49]
After writing the backend.py code , Im getting a win error 3 saying that it cant find the path specified to frames.
Anybody, please help

**Comment by kevinjycui** [comment]
Are you still getting this issue? Note that the setup docs only works out-of-the-box on Linux systems (specifically Ubuntu if you follow step-by-step).

Closing for now. Please re-open if you still need help.
