### ISSUE TITLE
Error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by BabyBoy666** [kevinjycui/DesmosBezierRenderer#5]
continuation of #4 
#4  worked and I installed potrace but when i ran backend.py it came up with a new error
```
Traceback (most recent call last):
  File "backend.py", line 77, in <module>
    frame_latex.append(get_latex(FRAME_DIR + '/frame%d.png' % (i+1)))
  File "backend.py", line 51, in get_latex
    path = get_trace(get_contours(filename))
  File "backend.py", line 29, in get_contours
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

pls help me

srry about all the issues

**Comment by kevinjycui** [comment]
This means the image that it's loading is empty. Did you create a folder `frames` and add files named `frames/frame%d.png` where %d represents the frame number starting from 1?

**Comment by BabyBoy666** [comment]
yeah, but mine are jpeg is there an edit to the code for that?

**Comment by kevinjycui** [comment]
Change [this line](https://github.com/kevinjycui/DesmosBezierRenderer/blob/master/backend.py#L77) from `.png` to `.jpg` or `.jpeg` (depending on what file extension your files are)

**Comment by BabyBoy666** [comment]
ok thanks!

**Comment by HyperTNT** [comment]
What line do i change, is it this line?
FILE_EXT = 'png' # Extension for frame files

When I changed it to 'jpg' it still didn't work and I am sure the image is a jpg. I also tried it with the sample image on png and it had the same error

**Comment by kevinjycui** [comment]
Are you sure you got the extension correct? What error are you getting? Note that you should put the exact extension (i.e. `jpg` and `jpeg` are different)
