### ISSUE TITLE
Taking sooo much time to render in HTML

### ISSUE THREAD

**Issue by sambuddha05** [kevinjycui/DesmosBezierRenderer#52]
HIi bro, thanks for your advice, Ive reached the final step, everything is done, the only problem it is taking lot of time for the images to appear in desmos html and images having greater file size aren't appearing at all.
Please help when you have time

**Comment by kevinjycui** [comment]
This is normal behaviour, Desmos is still a calculator website afterall. The only solution here is down-scaling the file dimensions. Hope that helps!

**Comment by sambuddha05** [comment]
thank bro
