### ISSUE TITLE
I can't seem to install all the requirements

### ISSUE THREAD

**Issue by RustLover2910** [kevinjycui/DesmosBezierRenderer#55]
Here` is the output from the `pip3 install -r requirements.txt`

`(env)` armstrong@NathansPC:~/DesmosBezierRenderer$ pip install -r requirements.txt 
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting Flask==1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Requirement already satisfied: Flask-Cors==3.0.10 in ./env/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (3.0.10)
Collecting itsdangerous==1.1.0
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2==2.11.3
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting kiwisolver==1.3.1
  Using cached kiwisolver-1.3.1.tar.gz (53 kB)
  Preparing metadata (setup.py) ... done
Collecting MarkupSafe==1.1.1
  Using cached MarkupSafe-1.1.1.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib==3.4.1
  Using cached matplotlib-3.4.1.tar.gz (37.3 MB)
  Preparing metadata (setup.py) ... done
Collecting numpy==1.23.0
  Using cached numpy-1.23.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
Collecting opencv-python==4.5.1.48
  Using cached opencv-python-4.5.1.48.tar.gz (88.3 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [323 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_machine != "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.6" and sys_platform == "linux" and platform_machine == "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_machine != "aarch64"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine != "aarch64"' don't match your environment
      Collecting setuptools
        Using cached setuptools-67.6.0-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting scikit-build
        Using cached scikit_build-0.16.7-py3-none-any.whl (79 kB)
      Collecting cmake
        Using cached cmake-3.25.2-py2.py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.7 MB)
      Collecting pip
        Using cached pip-23.0.1-py3-none-any.whl (2.1 MB)
      Collecting numpy==1.19.3
        Using cached numpy-1.19.3.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [286 lines of output]
            setup.py:67: RuntimeWarning: NumPy 1.19.3 may not yet support Python 3.10.
              warnings.warn(
            Running from numpy source directory.
            setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
              run_build = parse_setuppy_commands()
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_generator.pyx
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/_common.pyx
            Processing numpy/random/mtrand.pyx
            Processing numpy/random/_mt19937.pyx
            Processing numpy/random/bit_generator.pyx
            Processing numpy/random/_philox.pyx
            Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/_pcg64.pyx
            Cythonizing sources
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            blis_info:
              libraries blis not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            openblas_info:
              libraries openblas not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries tatlas not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_blas_info:
              libraries satlas not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_blas_threads_info:
            Setting PTATLAS=ATLAS
              libraries ptf77blas,ptcblas,atlas not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_blas_info:
              libraries f77blas,cblas,atlas not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            accelerate_info:
              NOT AVAILABLE
      
            /tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/system_info.py:1914: UserWarning:
                Optimized (vendor) Blas libraries are not found.
                Falls back to netlib Blas library which has worse performance.
                A better performance should be easily gained by switching
                Blas library.
              if self._calc_info(blas):
            blas_info:
              libraries blas not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            /tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/system_info.py:1914: UserWarning:
                Blas (http://www.netlib.org/blas/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [blas]) or by setting
                the BLAS environment variable.
              if self._calc_info(blas):
            blas_src_info:
              NOT AVAILABLE
      
            /tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/system_info.py:1914: UserWarning:
                Blas (http://www.netlib.org/blas/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [blas_src]) or by setting
                the BLAS_SRC environment variable.
              if self._calc_info(blas):
              NOT AVAILABLE
      
            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
              libraries mkl_rt not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            openblas_lapack_info:
              libraries openblas not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            openblas_clapack_info:
              libraries openblas,lapack not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            flame_info:
              libraries flame not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /home/armstrong/DesmosBezierRenderer/env/lib
              libraries tatlas,tatlas not found in /home/armstrong/DesmosBezierRenderer/env/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries tatlas,tatlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib64
              libraries tatlas,tatlas not found in /usr/lib64
              libraries lapack_atlas not found in /usr/lib
              libraries tatlas,tatlas not found in /usr/lib
              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
              libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
              NOT AVAILABLE
      
            atlas_3_10_info:
              libraries lapack_atlas not found in /home/armstrong/DesmosBezierRenderer/env/lib
              libraries satlas,satlas not found in /home/armstrong/DesmosBezierRenderer/env/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries satlas,satlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib64
              libraries satlas,satlas not found in /usr/lib64
              libraries lapack_atlas not found in /usr/lib
              libraries satlas,satlas not found in /usr/lib
              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
              libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
            <class 'numpy.distutils.system_info.atlas_3_10_info'>
              NOT AVAILABLE
      
            atlas_threads_info:
            Setting PTATLAS=ATLAS
              libraries lapack_atlas not found in /home/armstrong/DesmosBezierRenderer/env/lib
              libraries ptf77blas,ptcblas,atlas not found in /home/armstrong/DesmosBezierRenderer/env/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib64
              libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
              libraries lapack_atlas not found in /usr/lib
              libraries ptf77blas,ptcblas,atlas not found in /usr/lib
              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
              libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
            <class 'numpy.distutils.system_info.atlas_threads_info'>
              NOT AVAILABLE
      
            atlas_info:
              libraries lapack_atlas not found in /home/armstrong/DesmosBezierRenderer/env/lib
              libraries f77blas,cblas,atlas not found in /home/armstrong/DesmosBezierRenderer/env/lib
              libraries lapack_atlas not found in /usr/local/lib
              libraries f77blas,cblas,atlas not found in /usr/local/lib
              libraries lapack_atlas not found in /usr/lib64
              libraries f77blas,cblas,atlas not found in /usr/lib64
              libraries lapack_atlas not found in /usr/lib
              libraries f77blas,cblas,atlas not found in /usr/lib
              libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
              libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
            <class 'numpy.distutils.system_info.atlas_info'>
              NOT AVAILABLE
      
            lapack_info:
              libraries lapack not found in ['/home/armstrong/DesmosBezierRenderer/env/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            /tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/system_info.py:1748: UserWarning:
                Lapack (http://www.netlib.org/lapack/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [lapack]) or by setting
                the LAPACK environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()
            lapack_src_info:
              NOT AVAILABLE
      
            /tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/system_info.py:1748: UserWarning:
                Lapack (http://www.netlib.org/lapack/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [lapack_src]) or by setting
                the LAPACK_SRC environment variable.
              return getattr(self, '_calc_info_{}'.format(name))()
              NOT AVAILABLE
      
            numpy_linalg_lapack_lite:
              FOUND:
                language = c
                define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
      
            /tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running dist_info
            running build_src
            build_src
            building py_modules sources
            creating build
            creating build/src.linux-x86_64-3.10
            creating build/src.linux-x86_64-3.10/numpy
            creating build/src.linux-x86_64-3.10/numpy/distutils
            building library "npymath" sources
            Could not locate executable gfortran
            Could not locate executable f95
            Could not locate executable ifort
            Could not locate executable ifc
            Could not locate executable lf95
            Could not locate executable pgfortran
            Could not locate executable nvfortran
            Could not locate executable f90
            Could not locate executable f77
            Could not locate executable fort
            Could not locate executable efort
            Could not locate executable efc
            Could not locate executable g77
            Could not locate executable g95
            Could not locate executable pathf95
            Could not locate executable nagfor
            don't know how to compile Fortran code on platform 'posix'
            creating build/src.linux-x86_64-3.10/numpy/core
            creating build/src.linux-x86_64-3.10/numpy/core/src
            creating build/src.linux-x86_64-3.10/numpy/core/src/npymath
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/npymath/npy_math_internal.h
              adding 'build/src.linux-x86_64-3.10/numpy/core/src/npymath' to include_dirs.
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/npymath/ieee754.c
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/npymath/npy_math_complex.c
            None - nothing done with h_files = ['build/src.linux-x86_64-3.10/numpy/core/src/npymath/npy_math_internal.h']
            building library "npysort" sources
            creating build/src.linux-x86_64-3.10/numpy/core/src/common
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/common/npy_sort.h
              adding 'build/src.linux-x86_64-3.10/numpy/core/src/common' to include_dirs.
            creating build/src.linux-x86_64-3.10/numpy/core/src/npysort
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/npysort/quicksort.c
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/npysort/mergesort.c
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/npysort/timsort.c
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/npysort/heapsort.c
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/npysort/radixsort.c
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/common/npy_partition.h
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/npysort/selection.c
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/common/npy_binsearch.h
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/npysort/binsearch.c
            None - nothing done with h_files = ['build/src.linux-x86_64-3.10/numpy/core/src/common/npy_sort.h', 'build/src.linux-x86_64-3.10/numpy/core/src/common/npy_partition.h', 'build/src.linux-x86_64-3.10/numpy/core/src/common/npy_binsearch.h']
            building library "npyrandom" sources
            building extension "numpy.core._multiarray_tests" sources
            creating build/src.linux-x86_64-3.10/numpy/core/src/multiarray
            conv_template:> build/src.linux-x86_64-3.10/numpy/core/src/multiarray/_multiarray_tests.c
            building extension "numpy.core._multiarray_umath" sources
            Traceback (most recent call last):
              File "/home/armstrong/DesmosBezierRenderer/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/home/armstrong/DesmosBezierRenderer/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/home/armstrong/DesmosBezierRenderer/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
                return hook(metadata_directory, config_settings)
              File "/tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
                self.run_setup()
              File "/tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 248, in run_setup
                super(_BuildMetaLegacyBackend,
              File "/tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 142, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 508, in <module>
                setup_package()
              File "setup.py", line 500, in setup_package
                setup(**metadata)
              File "/tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/core.py", line 169, in setup
                return old_setup(**new_attr)
              File "/tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 165, in setup
                return distutils.core.setup(**attrs)
              File "/tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 31, in run
                egg_info.run()
              File "/tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/command/egg_info.py", line 24, in run
                self.run_command("build_src")
              File "/tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/tmp/pip-build-env-4aafzkv5/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()
              File "/tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/command/build_src.py", line 161, in build_sources
                self.build_extension_sources(ext)
              File "/tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/command/build_src.py", line 318, in build_extension_sources
                sources = self.generate_sources(sources, ext)
              File "/tmp/pip-install-l3qpg98s/numpy_1345717379684ff5b8294f82b7b5aff5/numpy/distutils/command/build_src.py", line 378, in generate_sources
                source = func(extension, build_dir)
              File "numpy/core/setup.py", line 436, in generate_config_h
                moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
              File "numpy/core/setup.py", line 47, in check_types
                out = check_types(*a, **kw)
              File "numpy/core/setup.py", line 292, in check_types
                raise SystemError(
            SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

I will provide any other information needed.
I am using Linux Mint.

**Comment by ariajd27** [comment]
Using the Ubuntu environment for Windows, the problem seems to be with numpy. With python 3.10, you have to `pip install numpy==1.24.2` and install the most recent version of opencv-python (so just `pip install opencv-python`). Then I just went down the list of packages in requirements.txt and manually installed each of them with pip so that `pip install -r` wouldn't give up upon encountering the numpy stuff. This worked for me and didn't take that long, and (I think) can be easily fixed by changing the requirements in requirements.txt.

**Comment by RustLover2910** [comment]
Thanks Mate It worked! Although it took lots of work around.
