### ISSUE TITLE
html wont work

### ISSUE THREAD

**Issue by cyberhero23** [kevinjycui/DesmosBezierRenderer#57]

**Comment by kevinjycui** [comment]
Please be more specific, I am not sure what the issue you are experiencing is.

**Comment by cyberhero23** [comment]
The HTML page freezes up, I was able to get it to display 1 frame before it froze up but that's the farthest I was able to get it to work.

**Comment by kevinjycui** [comment]
It sounds like it's just an issue of performance. Desmos is still a graphing calculator, after all. Try lowering the resolution of your source video.

**Comment by cyberhero23** [comment]
The source video was 1440p but I lowered it to 720p, I'll try 480p and if that doesn't work I'll keep lowering the resolution till it works by the way the specs of my laptop are 8gb of ram, intel core i5-5200U CPU 2.20GHz with 2 cores, intel HD graphics 5500. It's a laptop from 2015 so I can understand why it might struggle.
