### ISSUE TITLE
WSL linked can't be used

### ISSUE THREAD

**Issue by RealAkimFur** [kevinjycui/DesmosBezierRenderer#58]
The WSL that is linked in the instructions doesn't have the button to download it from the Windows Store 
![image](https://user-images.githubusercontent.com/123832635/233509418-7e8d79ab-0fc4-4970-abe8-fc05be19c134.png)
![image](https://user-images.githubusercontent.com/123832635/233509430-e8b54f80-bb7b-4842-a890-bdaf95d29972.png)

**Comment by kevinjycui** [comment]
I believe Windows has a new way to install WSL. Please see [this website](https://learn.microsoft.com/en-us/windows/wsl/install)
