### ISSUE TITLE
Command 'python' not found

### ISSUE THREAD

**Issue by RealAkimFur** [kevinjycui/DesmosBezierRenderer#59]
When trying to install requirements, I get this error message 
![image](https://user-images.githubusercontent.com/123832635/233758006-a01b044e-8c1a-4573-8cc4-7a5f05f39be2.png) ![image](https://user-images.githubusercontent.com/123832635/233757965-23d06121-0ecb-453a-8dd1-6276194d9624.png)

**Comment by kevinjycui** [comment]
You have Python installed as `python3`. Replace the command `python` with `python3` for each step (also if `pip` is not found later on, try `pip3`).
