### ISSUE TITLE
It reports error 

### ISSUE THREAD

**Issue by TXWG1911** [kevinjycui/DesmosBezierRenderer#65]
I did it in WSL. It report
txwg@DESKTOP-P3TFQTF:~/DesmosBezierRenderer$ python3 backend.py
Traceback (most recent call last):
  File "/home/txwg/DesmosBezierRenderer/backend.py", line 10, in <module>
    import cv2
  File "/home/txwg/.local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/txwg/.local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
[requirements.txt](https://github.com/kevinjycui/DesmosBezierRenderer/files/11538179/requirements.txt)

(I just random chose a file to upload, please do not mind)

**Comment by kevinjycui** [comment]
This is likely due to a missing package in your WSL environment. Try running `apt install libgl1`.

**Comment by TXWG1911** [comment]
Thanks！I will try

Kevin Junyang Cui ***@***.***> 於 2023年5月23日週二 下午12:05寫道：

**Comment by TXWG1911** [comment]
> This is likely due to a missing package in your WSL environment. Try running `apt install libgl1`.

![image](https://github.com/kevinjycui/DesmosBezierRenderer/assets/91261738/64524979-c78c-4ae3-83af-81df9fcb2dc8)
It still report error

**Comment by kevinjycui** [comment]
Be sure to follow [the instructions](https://github.com/kevinjycui/DesmosBezierRenderer#setup). Install all dependencies and do not run it with `sudo`.
