### ISSUE TITLE
Backend script not working

### ISSUE THREAD

**Issue by Brucewastaken** [kevinjycui/DesmosBezierRenderer#7]
When I followed the steps, backend.py does not start. After running python3 backend.py, it doesn't log anything. After moving app.run() up a little, it starts running. When I try to run the html, it returns a 404 error trying to run init and throws this error 
`uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.xhr.onload (desmos.html:27)`
Did I do something wrong?

**Comment by kevinjycui** [comment]
The `backend.py` script may take several minutes to preprocess the frames depending on the complexity and the number of frames (eg. the Zhongli example took about 5 minutes to process). Run the command and wait for the message to say that the server is running, then try it on the frontend.

**Comment by Brucewastaken** [comment]
okay, thanks! When I tried it, it seems to get stuck on cv2.waitKey(0). It works fine after removing them, and when I checked the docs it said it will wait until a key is pressed. Works fine after I removed it tho.
