### ISSUE TITLE
Usage on MacOS

### ISSUE THREAD

**Issue by rmart1n-dev** [kevinjycui/DesmosBezierRenderer#70]
I saw this, and thought it was very interesting. However, due to the fact that it was written for Linux (and windows i guess) (for example readme.md mentions linux and windows but not MacOS in any form.) I was just wondering how one might get the necessary packages to actually run this on a Mac, or if I would need to do something as crazy as a virtual machine. Thanks. Sorry if this is not an "issue" or if I just didn't read close enough.

**Comment by kevinjycui** [comment]
This has unfortunately not been supported. You can try just installing potrace and the other dependencies and trying, or turn to emulation. Sorry for the late response, it's been a busy few months.
