### ISSUE TITLE
command     --no-browser command doesn't work

### ISSUE THREAD

**Issue by berusssv5** [kevinjycui/DesmosBezierRenderer#71]
When I use the --no-browser suffix and don't open Chrome and fill in f=1, the script doesn't seem to start the training process, while training to a certain number of images (433 for me) in My Chrome reported an "Out of Memory" error and the script stopped the training process and forced me to start training again from the beginning and continued to get this error. Is there any way to fix it?
Also, I want to ask, is there any way I can continue my training process when Chrome crashes?
![Screenshot (94)](https://github.com/kevinjycui/DesmosBezierRenderer/assets/63569635/579739c3-ed31-40a5-8b8f-02b66f230313)

**Comment by kevinjycui** [comment]
Hello! This error is likely not to do with the --no-browser flag but rather simply that your computer ran out of memory to run the program. Try a smaller animation, either by lowering the quality of the video or shortening it.
