### ISSUE TITLE
backend.py is working

### ISSUE THREAD

**Issue by pwned2** [kevinjycui/DesmosBezierRenderer#9]
when i run it it just kills it self

**Comment by pwned2** [comment]
it gives me a message that just says killed

**Comment by kevinjycui** [comment]
It could be an issue with memory. What are you trying to render?

**Comment by kevinjycui** [comment]
Closing for now due to inactivity

**Comment by hassaan253** [comment]
Hello, I'm facing the same issue, 
I let it stay running for about half an hour but only the f= 1 function on the desmos front end was sliding back and forth and nothing was rendering. 
Could you please help in any way
thanks
